#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tpk4128-opencv-camera','console_scripts','opencv_camera_node'
__requires__ = 'tpk4128-opencv-camera'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tpk4128-opencv-camera', 'console_scripts', 'opencv_camera_node')()
    )
